### PR TITLE
DI-199 Create Performance tests

### PR DESCRIPTION
**Pull request by JackPlowman**
## Link to JIRA Ticket

- https://nhsd-jira.digital.nhs.uk/browse/DI-199

## Description

This PR add two performance test profiles a stress test and a load test.

### Noteworthy Changes

- A stress test creating large quantities of change events upfront (around 20K CEs per minute)
- A load test designed to simulate standard CE quantiess (around 20 CEs per minute)
- A data collection part to pickup all data and put it to a s3 bucket

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Developer Checklist

- [x] I have performed a self-review of my own code
- [x] I have run the [code formatting checks](../README.md#code-quality)
- [x] I have run the [code quality checks](../README.md#code-quality)
- [x] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [x] Unit test code coverage is at or above 80%
- [x] New and existing unit tests pass locally with my changes
- [x] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

### CODE REVIEW

**Review by rohith1122 — COMMENTED** [review]
Code is looks good 
but when I run the  make performance-test-data-collection PROFILE=perf ENVIRONMENT=perf START_TIME=2022-01-26_12-35-55 END_TIME=2022-01-26_12-46-50

Exception Occurred when getting metrics results: Metric=ProcessingLatency Exception='Timestamp'
Exception Occurred when getting metrics results: Metric=DosApiLatency Exception='Timestamp'
Exception Occurred when getting metrics results: Metric=DoSApiFail Exception='Timestamp'

image

**Review by rohith1122 — COMMENTED** [review]
fixed the load-test  issue 
image

getting an issue with the stress-test 

image

**Comment by JackPlowman** [comment]
> fixed the load-test issue image
> 
> getting an issue with the stress-test
> 
> image

I get this issue when I use to many users for my CPU to be able to handle. @rohith1122 If you turn down the number of users does it get rid of this issue? 
In the performance pipeline which these tests are going to run from we could set the performance of the codebuild instance so we can scale so to not error when running the stress test. Or we can turn down the stress test as at the moment it is overkill roughly double the number of NHS UK pharmacies

**Review by ed-sparkes — APPROVED** [review]

**Review by ed-sparkes — CHANGES_REQUESTED** [review]
Please can you add the data output etc to gitignore

**Review by ed-sparkes — APPROVED** [review]

**Review by rohith1122 — APPROVED** [review]
LGTM

**Review by mabe13 — APPROVED** [review]

**Review by rohith1122 — APPROVED** [review]

**Pull request merged**
